CREATE TABLE [dbo].[Smileys](
	[id_Smiley] [int] IDENTITY(1,1) NOT NULL,
	[Label] [varchar](20) NOT NULL,
 CONSTRAINT [PK_Smileys] PRIMARY KEY CLUSTERED 
(
	[id_Smiley] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]